# Mathematical Basis I

## 1 Divisibility and Congruences

Prove that $n$ is divisible by $9$, i.e. $9\ |\ n$, if the sum of the
digits of $n$ is divisible by $9$. Hint: use the identity $10 = 9+1$.

$n=d_m\cdot10^m+d_{m-1}\cdot10(m-1)+\cdots+d_2\cdot10^2+d_1\cdot10+d_0$

$10^n=(9+1)^n=\displaystyle\sum_{k=0}^{n} \binom{n}{k} 9^{n-k}1^k$

$n\equiv_9 \displaystyle\sum_{i=0}^{n} d_i+10^i \equiv_9 \displaystyle\sum_{i=0}^{n} d_i \cdot \displaystyle\sum_{k=0}^{n} \binom{n}{k} 9^{n-k}1^k \equiv_9 \displaystyle\sum_{i=0}^{n} d_i \cdot 1 \equiv_9 \displaystyle\sum_{i=0}^{n} d_i$

## 3 Computing the (multiplicative) inverse I

The multiplicative inverse of a modulo n exists iff (if and only if) gcd(a;n) = 1. If this is the
case, it can be computed using the extended GCD algorithm. This amounts to find x and y s.t.
(such that)

$ax+ ny = gcd(a;n) = 1:$

As an example with n = 47 and a = 12 we have

$12 ·4+47 ·(−1) = gcd(12;47) = 1:$

If take both sides of this equation modulo 47, we get

(12 ·4+47 ·(−1)) mod 47 = 1;
(12 ·4) mod 47 = 1;

This tells us, that 4 is the (multiplicative) inverse of 12 modulo 47. In fact 12 ·4 mod 47 = 48
mod 47 = 1.

**Your Task:** Find the multiplicative inverses of a modulo n (if it exists) if

In [1]:
def EuclideanGCD(a,b):
    while b:
        a,b = b, a % b
    return a

In [3]:
EuclideanGCD(47,8)

1

A function for displaying the summary of a notebook object.
It prints a simple summary, such as:

```
  1   markdown cells, total:   4 lines
  5       code cells, total:   4 lines
  1    heading cells, total:   1 lines
```

In [5]:
def ExtendedGCD(a,b):
   # initialization
    s1 = a; s2 = b
    u1 = 1; u2 = 0
    v1 = 0; v2 = 1
    while s2 > 0: # loop if not finished
        q = s1 // s2
        r = s1 % s2
        s1 = s2; s2 = r
        t = u2; u2 = u1 - q*u2; u1 = t
        t = v2; v2 = v1 - q*v2; v1 = t
    return u1, v1, s1

In [6]:
ExtendedGCD(47,8)

(-1, 6, 1)

In [7]:
ExtendedGCD(202,71)

(-13, 37, 1)

## 4 Computing the (multiplicative) inverse II

Which of the elements in $\mathbb{Z}_6$ do have a (multiplicative) inverse modulo $6$? For each of these
elements compute the inverse and prove, that it is indeed the inverse by computing $a\cdot a^{−1}\ \text{mod}\ 6$.

In [41]:
import numpy as np
i = np.arange(1,6)
for j in range(1,6):
    print(str(j) + ": ")
    print(np.mod((i*j),6))

1: 
[1 2 3 4 5]
2: 
[2 4 0 2 4]
3: 
[3 0 3 0 3]
4: 
[4 2 0 4 2]
5: 
[5 4 3 2 1]


In [37]:
(1*1)%6

1